server:
  port: 8088

# 配置mysql,根据url自动识别Driver
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 13013005866

mybatis:
  config-location: classpath:mybatis-config.xml